### ISSUE TITLE
SyntaxError: expected expression, got '<' o

### ISSUE THREAD

**Issue by DennieMello** [flaming-cl/editorjs-math#1]
After adding to the editor it gives an error:

```
SyntaxError: expected expression, got '<'
o
node_modules/editorjs-math/dist/bundle.js:9
```

**Comment by flaming-cl** [comment]
Hi. Thanks for your feedback.
I've updated a new version of the plugin. The problem you've mentioned should be fixed now.
If you have any other questions, please feel free to let me know.
Also, if you would like to, you can try the plugin in this demo: https://flaming-cl.github.io/editorPlugin/

**Comment by DennieMello** [comment]
> Hi. Thanks for your feedback.
> I've updated a new version of the plugin. The problem you've mentioned should be fixed now.
> If you have any other questions, please feel free to let me know.
> Also, if you would like to, you can try the plugin in this demo: https://flaming-cl.github.io/editorPlugin/

Thank you!
